# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/corsica/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/corsica/proprietary/bin/BCM4330B1_002.001.003.0967.1089.hcd:system/bin/BCM4330B1_002.001.003.0967.1089.hcd \
    vendor/samsung/corsica/proprietary/bin/bkmgrd:system/bin/bkmgrd \
    vendor/samsung/corsica/proprietary/bin/cate_rpc_util:system/bin/cate_rpc_util \
    vendor/samsung/corsica/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/corsica/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/corsica/proprietary/bin/gpslogd:system/bin/gpslogd \
    vendor/samsung/corsica/proprietary/bin/immvibed:system/bin/immvibed \
    vendor/samsung/corsica/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/corsica/proprietary/bin/mttlogger:system/bin/mttlogger \
    vendor/samsung/corsica/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/corsica/proprietary/bin/bluetoothd:system/bin/bluetoothd \
    vendor/samsung/corsica/proprietary/bin/p2p_supplicant:system/bin/p2p_supplicant \
    vendor/samsung/corsica/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/corsica/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/corsica/proprietary/etc/asound.conf:system/etc/asound.conf \
    vendor/samsung/corsica/proprietary/etc/DiamondVoice.txt:system/etc/DiamondVoice.txt \
    vendor/samsung/corsica/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/corsica/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/corsica/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/corsica/proprietary/etc/Volume.db:system/etc/Volume.db \
    vendor/samsung/corsica/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/corsica/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/corsica/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/corsica/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/corsica/proprietary/etc/gps/glconfig.xml:system/etc/gps/glconfig.xml \
    vendor/samsung/corsica/proprietary/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/samsung/corsica/proprietary/lib/hw/audio.primary.rhea.so:system/lib/hw/audio.primary.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/camera.rhea.so:system/lib/hw/camera.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/gps.rhea.so:system/lib/hw/gps.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/gralloc.rhea.so:system/lib/hw/gralloc.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/hwcomposer.rhea.so:system/lib/hw/hwcomposer.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/lights.rhea.so:system/lib/hw/lights.rhea.so \
    vendor/samsung/corsica/proprietary/lib/hw/sensors.rhea.so:system/lib/hw/sensors.rhea.so \
    vendor/samsung/corsica/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/samsung/corsica/proprietary/lib/libat.so:system/lib/libat.so \
    vendor/samsung/corsica/proprietary/lib/libat_stubs.so:system/lib/libat_stubs.so \
    vendor/samsung/corsica/proprietary/lib/libbrcmcutils.so:system/lib/libbrcmcutils.so \
    vendor/samsung/corsica/proprietary/lib/libbrcmparser.so:system/lib/libbrcmparser.so \
    vendor/samsung/corsica/proprietary/lib/libbrcm_ril.so:system/lib/libbrcm_ril.so \
    vendor/samsung/corsica/proprietary/lib/libcapi2.so:system/lib/libcapi2.so \
    vendor/samsung/corsica/proprietary/lib/libcate_rpc.so:system/lib/libcate_rpc.so \
    vendor/samsung/corsica/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/corsica/proprietary/lib/libImmVibeJ.so:system/lib/libImmVibeJ.so \
    vendor/samsung/corsica/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/corsica/proprietary/lib/librpc.so:system/lib/librpc.so \
    vendor/samsung/corsica/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/corsica/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/corsica/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/corsica/proprietary/lib/lib_SamsungRec_V02002.so:system/lib/lib_SamsungRec_V02002.so \
    vendor/samsung/corsica/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/corsica/proprietary/lib/libseckeyprov.so:system/lib/libseckeyprov.so \
    vendor/samsung/corsica/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/corsica/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/corsica/proprietary/lib/libsoc.so:system/lib/libsoc.so \
    vendor/samsung/corsica/proprietary/lib/lib_SoundAlive_V01013h.so:system/lib/lib_SoundAlive_V01013h.so \
    vendor/samsung/corsica/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/corsica/proprietary/lib/libSoundAlive_VSP_ver312a.so:system/lib/libSoundAlive_VSP_ver312a.so \
    vendor/samsung/corsica/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/corsica/proprietary/lib/libuecodec.so:system/lib/libuecodec.so \
    vendor/samsung/corsica/proprietary/lib/libusb_config.so:system/lib/libusb_config.so \
    vendor/samsung/corsica/proprietary/lib/libVCOS.so:system/lib/libVCOS.so \
    vendor/samsung/corsica/proprietary/lib/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \
    vendor/samsung/corsica/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/corsica/proprietary/lib/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/corsica/proprietary/lib/modules/VoiceSolution.ko:system/lib/modules/VoiceSolution.ko \
    vendor/samsung/corsica/proprietary/lib/egl/libGLES_rhea.so:system/lib/egl/libGLES_rhea.so \
    vendor/samsung/corsica/proprietary/lib/libacdapi_azi.so:system/lib/libacdapi_azi.so \
    vendor/samsung/corsica/proprietary/lib/libbralloc.so:system/lib/libbralloc.so \
    vendor/samsung/corsica/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/corsica/proprietary/lib/libFraunhoferAAC.so:system/lib/libFraunhoferAAC.so \
    vendor/samsung/corsica/proprietary/lib/libisp2.so:system/lib/libisp2.so \
    vendor/samsung/corsica/proprietary/lib/libISP.so:system/lib/libISP.so \
    vendor/samsung/corsica/proprietary/lib/liblvvefs.so:system/lib/liblvvefs.so \
    vendor/samsung/corsica/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/corsica/proprietary/lib/libV3D_csc.so:system/lib/libV3D_csc.so \
    vendor/samsung/corsica/proprietary/lib/libV3D_driver.so:system/lib/libV3D_driver.so \
    vendor/samsung/corsica/proprietary/lib/libV3D_server.so:system/lib/libV3D_server.so \
    vendor/samsung/corsica/proprietary/lib/libVCE_imageconv.so:system/lib/libVCE_imageconv.so \
    vendor/samsung/corsica/proprietary/lib/libVCE_csl.so:system/lib/libVCE_csl.so \
    vendor/samsung/corsica/proprietary/lib/libVCE_driver.so:system/lib/libVCE_driver.so \
    vendor/samsung/corsica/proprietary/lib/libVCE_vtq.so:system/lib/libVCE_vtq.so \
    vendor/samsung/corsica/proprietary/lib/libvtqinit.so:system/lib/libvtqinit.so \
    vendor/samsung/corsica/proprietary/lib/libvpx_dec.so:system/lib/libvpx_dec.so \
    vendor/samsung/corsica/proprietary/lib/libdeblock.so:system/lib/libdeblock.so \
    vendor/samsung/corsica/proprietary/lib/libv3d.so:system/lib/libv3d.so \
    vendor/samsung/corsica/proprietary/lib/libtiming.so:system/lib/libtiming.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.decoder.mpeg4.so:system/lib/libOMX.brcm.video.decoder.mpeg4.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.encoder.mpeg4.so:system/lib/libOMX.brcm.video.encoder.mpeg4.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.decoder.vpx.so:system/lib/libOMX.brcm.video.decoder.vpx.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.encoder.h264.so:system/lib/libOMX.brcm.video.encoder.h264.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.decoder.h264.so:system/lib/libOMX.brcm.video.decoder.h264.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.encoder.h263.so:system/lib/libOMX.brcm.video.encoder.h263.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.decoder.h263.so:system/lib/libOMX.brcm.video.decoder.h263.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.encoder.dummy.so:system/lib/libOMX.brcm.video.encoder.dummy.so \
    vendor/samsung/corsica/proprietary/lib/libOMX.brcm.video.decoder.dummy.so:system/lib/libOMX.brcm.video.decoder.dummy.so \
    vendor/samsung/corsica/proprietary/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so:system/usr/lib/alsa-lib/libasound_module_pcm_bcmfilter.so \
    vendor/samsung/corsica/proprietary/usr/lib/alsa-lib/libbcm_hp_filter.so:system/usr/lib/alsa-lib/libbcm_hp_filter.so \
    vendor/samsung/corsica/proprietary/usr/lib/alsa-lib/libbcm_test_filter.so:system/usr/lib/alsa-lib/libbcm_test_filter.so \
    vendor/samsung/corsica/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
